modules/admin/controllers/NutritionController.php
<?php

namespace app\modules\admin\controllers;
use app\models\form\NutritionForm;
use app\models\Nutrition;
use app\models\base\ProductNutrition;
use app\models\NutritionTranslation;
use cornernote\returnurl\ReturnUrl;
use Yii;
use yii\filters\AccessControl;

/**
 * This is the class for controller "app\controllers\NutritionController".
 */
class NutritionController extends \app\modules\admin\controllers\base\NutritionController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['guest']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'get-nutrition-for-product'],
                        'roles' => ['admin']
                    ]
                ]
            ]
        ];
    }

    public $nutritionTranslation;

    public function actionView($id)
    {
        $model = $this->findModel($id);
        $modelTranslation = NutritionTranslation::find()->where(['nutrition_id' => $id])->one();

        $nutritionModel = new NutritionForm();
        $nutritionModel->setNutrition($model);
        $nutritionModel->setNutritionTranslation($modelTranslation);
        return $this->render('view', ['model' => $nutritionModel]);
    }

    public function actionCreate()
    {
        $model = new Nutrition();
        $nutritionModel = new NutritionForm();
        $nutritionModel->scenario = 'create';
        if (Yii::$app->request->post()) {
            $model->attributes = $_POST['Nutrition'];
            if($model->save()){
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Nutrition has been '.$nutritionModel->scenario.'d .'));
                if(Yii::$app->request->post()['NutritionTranslation']['language_id']!=''){
                    $this->nutritionTranslation = new NutritionTranslation();
                    $this->nutritionTranslation->attributes = $_POST['NutritionTranslation'];
                    $this->nutritionTranslation->nutrition_id = $model->id;
                    if($this->nutritionTranslation->save(false)) {
                        Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Nutrition has been '.$nutritionModel->scenario.'d and translated.'));
                    }
                }
                $nutritionModel->setNutrition($model);
                $nutritionModel->setNutritionTranslation($this->nutritionTranslation);
                return $this->redirect(['view', 'id' => $model->id, 'ru' => ReturnUrl::getRequestToken()]);
            }
        }
        return $this->render('create', ['model' => $nutritionModel]);
    }


    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $nutritionModel = new NutritionForm();
        $nutritionModel->scenario = 'update';
        if (Yii::$app->request->post()) {
            $model->attributes = $_POST['Nutrition'];
            if($model->save(true)){
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Nutrition has been '.$nutritionModel->scenario.'d .'));

                if(Yii::$app->request->post()['NutritionTranslation']['language_id']!=''){
                    $this->nutritionTranslation = NutritionTranslation::find()->where(['nutrition_id' => $model->id, 'language_id' => $_POST['NutritionTranslation']['language_id'] ])->one();
                    if (isset($this->nutritionTranslation)) {
                        $this->nutritionTranslation->attributes = $_POST['NutritionTranslation'];
                        $this->nutritionTranslation->nutrition_id = $model->id;
                    } else {
                        $this->nutritionTranslation = new NutritionTranslation();
                        $this->nutritionTranslation->attributes = $_POST['NutritionTranslation'];
                        $this->nutritionTranslation->nutrition_id = $model->id;
                    }
                    if($this->nutritionTranslation->save(false)) {
                        Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Nutrition  has been '.$nutritionModel->scenario.'d and translated.'));
                    }
                }
                $nutritionModel->setNutrition($model);
                $nutritionModel->setNutritionTranslation($this->nutritionTranslation);
                return $this->redirect(['view', 'id' => $model->id, 'ru' => ReturnUrl::getRequestToken()]);
            }
        }
        $nutritionModel->setNutrition($model);
        $nutritionModel->setNutritionTranslation($this->nutritionTranslation);
        return $this->render('update', ['model' => $nutritionModel]);
    }


    /**
     * Returns all existing ProductNutrition models.
     * @return ProductNutrition[]
     */
    public function actionGetNutritionForProduct()
    {
        $productNutritions = [];
        $nutritions  = Nutrition::find()->all();

//        print_r($nutritions);

        foreach ($nutritions as $nutrition){

            $productNutrition = ProductNutrition::find()->where(['product_id' => $_POST['product_id'],'nutrition_id' => $nutrition->id ])->one();

            if(isset($productNutrition)){
                array_push($productNutritions,$productNutrition);
            }else{
                $productNutrition = new ProductNutrition;
                $productNutrition->scenario = 'create';
                $productNutrition->nutrition_id = $nutrition->id;
                $productNutrition->product_id = $_POST['product_id'];
                array_push($productNutritions,$productNutrition);
            }
        }
        if(count($productNutritions)){
            return $this->renderAjax('product-nutrition', ['model' => $productNutritions]);
        }
    }


}

modules/admin/views/nutrition/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\form\NutritionForm $model
 * @var yii\bootstrap\ActiveForm $form
 */

?>

<div class="brand-form">
    <?php $form = ActiveForm::begin([
        'id' => 'Nutrition',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-lg-4',
                'wrapper' => 'col-lg-8',
                'error' => '',
                'hint' => '',
            ],
        ],
        'enableClientValidation' => false,
    ]); ?>

    <?= Html::hiddenInput('ru', ReturnUrl::getRequestToken()); ?>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <hr class="hr">
            <h1>Nutrition</h1>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 oziris-block">
            <div class="row" style="padding-top: 20px ;padding-right: 20px">
                <?= $form->field($model->nutrition, 'name')->textInput(['maxlength' => true]) ?>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <h1>Nutrition Translation</h1>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 oziris-block">
            <div class="row" style="padding-top: 20px">
                <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model->nutritiontranslation, 'language_id')->widget(\kartik\select2\Select2::classname(), [
                    'name' => 'class_name',
                    'model' => $model->nutritiontranslation,
                    'attribute' => 'language_id',
                    'data' => \yii\helpers\ArrayHelper::map(app\models\Language::find()->all(), 'id', 'name'),
                    'options' => [
                        'placeholder' => Yii::t('app', 'Type to autocomplete'),
                        'multiple' => false,
                    ]
                ]); ?>

                <?= $form->field($model->nutritiontranslation, 'name')->textInput(['maxlength' => true]) ?>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="pull-right" style="padding-top: 20px">
                <?= Html::submitButton('<span class="fa fa-check"></span> ' . ($model->nutrition->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')), [
                    'id' => 'save-' . $model->nutrition->formName(),
                    'class' => 'btn btn-oziris-save'
                ]); ?>
                <?php if ($model->nutrition->isNewRecord) echo Html::a('<span class="fa fa-times"></span> ' . Yii::t('app', 'Cancel'), ReturnUrl::getUrl(['index']), ['class' => 'btn btn-oziris-normal']) ?>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

modules/admin/views/nutrition/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\Nutrition $model
 */

$this->title = Yii::t('app', 'Create Nutrition');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Nutritions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nutrition-create">

    <?= $this->render('@app/views/layouts/_menu', ['model' => $model]) ?>
    <?= $this->render('_form', ['model' => $model,]); ?>

</div>

modules/admin/views/nutrition/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ButtonDropdown;
use yii\grid\GridView;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\NutritionSearch $searchModel
 */

$this->title = Yii::t('app', 'Nutrition');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="nutrition-index">

    <div class="clearfix">

        <table width="100%">
            <tr>
                <td>
                    <h1 class="pull-left"><?= $this->title ?></h1>
                </td>
                <td>
                    <div class="pull-right">
                        <?= Html::a('<span class="fa fa-plus"></span> ' . Yii::t('app', 'Create') . ' ' . Yii::t('app', 'Nutrient'), ['create', 'ru' => ReturnUrl::getToken()], ['class' => 'btn btn-oziris']) ?>
                    </div>
                </td>
            </tr>
        </table>
        <hr class="hr">
    </div>

    <div class="text-center">
        <?= \kartik\grid\GridView::widget([
            'layout' => '{summary}{pager}{items}{pager}',
            'dataProvider' => $dataProvider,
            'pager' => [
                'class' => yii\widgets\LinkPager::className(),
                'firstPageLabel' => Yii::t('app', 'First'),
                'lastPageLabel' => Yii::t('app', 'Last'),
            ],
            'filterModel' => $searchModel,
            'responsive' => true,
            'hover'=>true,
            'export' => false,
            'columns' => [

                [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'id',
                    'value' => function ($model) {
                            return Html::a($model->id, ['nutrition/view', 'id' => $model->id,], ['data-pjax' => 0]);
                    },
                    'format' => 'raw',
                ],
                [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'name',
                    'label' => 'Nutrient',
                    'value' => function ($model) {
                            return Html::a($model->name, ['nutrition/view', 'id' => $model->id,], ['data-pjax' => 0]);

                    },
                    'format' => 'raw',
                ],
                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{update}',
                    'contentOptions' => ['nowrap' => 'nowrap']
                ],
            ],
        ]); ?>
    </div>
</div>

modules/admin/views/nutrition/product-nutrition.php
<?php

/**
 * @var yii\web\View $this
 * @var app\models\ProductNutrition[] $model
 * @var yii\bootstrap\ActiveForm $form
 */
use cornernote\returnurl\ReturnUrl;
use dmstr\helpers\Html;
use Symfony\Component\Console\Input\Input;

?>

<div class="text-center" id="product-nutrition-div">

    <?= Html::hiddenInput('ru', ReturnUrl::getRequestToken()); ?>
    <?= Html::hiddenInput('no_of_nutrition', count($model)); ?>
    <div class="row">
            <h1 class="pull-left">Nutrition Information</h1>
    </div>
    <div class="row">
        <table class="kv-grid-table table table-bordered table-striped kv-table-wrap">
            <thead>
            <tr>
                <th colspan="3">Nutrition Information</th>
            </tr>

            <tr>
                <th></th>
                <th>Average Quantity </br> per Serving </th>
                <th>Average Quantity </br> per 100g (or 100 mL)</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($model as $index => $nutrition) { ?>
                <tr>
                    <td class="text-left" style="width: 40%"><label class="control-label"><?= $nutrition->nutrition->name ?></label></td>
                    <?= Html::hiddenInput('nutrition_id-'.$index, $nutrition->nutrition_id); ?>
                    <td style="width: 30%"><?= Html::input('text','nutrition_per_serve-'.$index,$nutrition->avg_qty_per_serving); ?></td>
                    <td style="width: 30%"><?= Html::input('text','nutrition_per_100g-'.$index,$nutrition->avg_qty_per_100g); ?></td>
                </tr>
            <?php } ?>

            </tbody>
        </table>
    </div>
</div>

modules/admin/views/nutrition/update.php
<?php

use yii\helpers\Html;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\form\NutritionForm $model
 */

$this->title = Yii::t('app', 'Update') . ' ' . Yii::t('app', 'Nutrition') . ' - ' . $model->getNutrition()->name;
?>
<div class="nutrition-update">

    <?= $this->render('@app/views/layouts/_menu', ['model' => $model->getNutrition()]) ?>
    <?php echo $this->render('_form', ['model' => $model,]); ?>

</div>

modules/admin/views/nutrition/view-nutrition.php
<?php

/**
 * @var yii\web\View $this
 * @var app\models\ProductNutrition[] $model
 * @var yii\bootstrap\ActiveForm $form
 */
use cornernote\returnurl\ReturnUrl;
use dmstr\helpers\Html;
use Symfony\Component\Console\Input\Input;

?>

<div class="text-center" id="product-nutrition-div">
    <div class="row">
            <h1 class="pull-left">Nutrition Information</h1>
            <button id="saveNutritionTable" class="pull-right">Generate Nutrition Information</button>
    </div>
    <div id="nutrition-table" class="row">
        <table style="border:  1px solid #000000;border-spacing: 0px"  bgcolor="#FFFFFF" class="table">
            <thead>
            <tr style="1px solid #000000;">
                <th bgcolor="#808080" style="color: white" colspan="3">Nutritional Information</th>
            </tr>
            <tr style="border-top: 1px solid #000000;">
                <th bgcolor="#FFFFFF" colspan="3"><?= $serves_per_pack?> Serves per pack, Serving size <?= $serve_size?></th>
            </tr>

            <tr style="border-top: 1px solid #000000;!important;">
                <th style="border: 1px solid #000000;!important;">Average Quantity</th>
                <th style="border: 1px solid #000000;!important;" >per Serving </th>
                <th style="border: 1px solid #000000;!important;">per 100g (or 100 mL)</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($model as $index => $nutrition) {
                ?>
                <tr style="border: 1px solid #000000;">
                    <td class="text-left" style="border-right: 1px solid #000000;" style="width: 40%"><label class="control-label"><?= $nutrition->nutrition->name ?></label></td>
                    <td style="width: 30% ; border-right: 1px solid #000000;"><label class="control-label"><?= $nutrition->avg_qty_per_serving ?></label></td>
                    <td style="width: 30% ; border-right: 1px solid #000000;"><label class="control-label"><?= $nutrition->avg_qty_per_100g?></label></td>
                </tr>
            <?php } ?>

            <?php
                $ingredientString = 'Ingredients : ';
                foreach($ingredients as $ingredient){
                    $ingredientString .= $ingredient->ingredient->name.', ';
                }

            ?>

            <tr style="1px solid #000000;">
                <td colspan="3"><p style="  font-size: 10px"><?= $nutrition_text ?> <br/><br/> <?= $ingredientString ?></p></td>
            </tr>
            </tbody>

        </table>
    </div>
</div>

modules/admin/views/nutrition/view.php
<?php

/**
 * @var yii\web\View $this
 * @var app\models\form\NutritionForm $model
 */

use kartik\detail\DetailView;

$this->title = Yii::t('app', 'Nutrition') . ' ' . $model->nutrition->name;
?>


<div class="brand-view">

    <?= $this->render('@app/views/layouts/_menu', ['model' => $model->nutrition]) ?>
    <hr class="hr">

    <div>
        <div class="row">
            <div class="col-lg-1 no-padding-right">

            </div>
            <div class="col-lg-10">
                <?php
                echo DetailView::widget([
                    'model' => $model->nutrition,
                    'attributes' => [
                        [
                            'group' => true,
                            'label' => 'Nutrition Information',
                            'rowOptions' => ['class' => 'product-info-header']
                        ],
                        [
                            'columns' => [
                                [
                                    'attribute' => 'id',
                                    'format' => 'raw',
                                    'value' => '<kbd>' . $model->nutrition->id . '</kbd>',
                                    'labelColOptions' => ['style' => 'width:30%'],
                                    'valueColOptions' => ['style' => 'width:70%'],
                                    'displayOnly' => true,
                                ],
                            ],
                        ],
                        [
                            'columns' => [
                                [
                                    'attribute' => 'name',
                                    'format' => 'raw',
                                    'value' => $model->nutrition->name,
                                    'labelColOptions' => ['style' => 'width:30%'],
                                    'valueColOptions' => ['style' => 'width:70%'],
                                    'displayOnly' => false
                                ],
                            ],
                        ]
                    ],
                    'mode' => 'view',
                    'bordered' => false,
                    'striped' => true,
                    'condensed' => true,
                    'responsive' => true,
                    'hover' => true,
                    'hAlign' => 'left',
                    'vAlign' => 'middle',
                    'fadeDelay' => 200,
                    'class'=> 'text-left',
                ]);
                ?>
                <?= DetailView::widget([
                    'model' => $model->getNutritionTranslation(),
                    'attributes' => [
                        'name',
                    ],
                ]);
                ?>

            </div>


            <div class="col-lg-1"></div>

        </div>
    </div>
</div>