modules/admin/controllers/ProductGroupController.php
<?php

namespace app\modules\admin\controllers;
use app\models\Product;
use app\models\ProductGroupTranslation;
use app\models\form\ProductGroupForm;
use Yii;
use cornernote\returnurl\ReturnUrl;
use dmstr\bootstrap\Tabs;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;


/**
 * This is the class for controller "app\modules\admin\controllers\ProductGroupController".
 */
class ProductGroupController extends \app\modules\admin\controllers\base\ProductGroupController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['guest']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'change-status'],
                        'roles' => ['admin']
                    ]
                ]
            ]
        ];
    }


    public $productGroupTranslation;
    /**
     * Displays a single ProductGroup model.
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $modelTranslation = ProductGroupTranslation::findOne(['id' => $id]);
        $productGroupModel = new ProductGroupForm();
        $productGroupModel->setProductGroup($model);
        $productGroupModel->setProductGroupTranslation($modelTranslation);
        return $this->render('view', ['model' => $productGroupModel]);
    }
    
    /**
     * Updates an existing ProductGroup and ProductGroup Translation model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */


    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $productGroupModel = new ProductGroupForm();
        $productGroupModel->scenario = 'update';
        if (Yii::$app->request->post()) {
            $model->product_group_name=Yii::$app->request->post()['ProductGroup']['product_group_name'];
            $model->show_on_menu=Yii::$app->request->post()['ProductGroup']['show_on_menu'];
            if($model->save(true)){
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Product Group has been '.$productGroupModel->scenario.'d .'));
                if(Yii::$app->request->post()['ProductGroupTranslation']['language_id']!=''){
                    $this->productGroupTranslation = ProductGroupTranslation::find()->where(['product_group_id' => $model->id, 'language_id' => $_POST['ProductGroupTranslation']['language_id'] ])->one();
                    if (isset($this->productGroupTranslation)) {
                        $this->productGroupTranslation->attributes = $_POST['ProductGroupTranslation'];
                        $this->productGroupTranslation->product_group_id = $model->id;
                    } else {
                        $this->productGroupTranslation = new ProductGroupTranslation();
                        $this->productGroupTranslation->attributes = $_POST['ProductGroupTranslation'];
                        $this->productGroupTranslation->product_group_id = $model->id;
                    }
                    if($this->productGroupTranslation->save()) {
                        Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Product Group  has been '.$productGroupModel->scenario.'d and translated.'));
                    }
                 }
                $productGroupModel->setProductGroup($model);
                $productGroupModel->setProductGroupTranslation($this->productGroupTranslation);
                return $this->redirect(['view', 'id' => $model->id, 'ru' => ReturnUrl::getRequestToken()]);
            }
        }
        $productGroupModel->setProductGroup($model);
        $productGroupModel->setProductGroupTranslation($this->productGroupTranslation);
        return $this->render('update', ['model' => $productGroupModel]);
    }

    /**
     * Enables/Disables an existing ProductGroup model.
     * If update is successful, the browser will refresh 'Index' page to reflect changes.
     * @param integer $id
     * @return mixed
     */
    public function actionChangeStatus($id)
    {


        $this->findModel($id)->changeStatus();
        return $this->redirect('index');
    }

//        $query = Product::find()->where(['product_group_id' => $id]);
//
//        $dataProvider = new ActiveDataProvider([
//            'query' => $query,
//            //'sort' => ['defaultOrder' => ['id' => SORT_DESC]],
//        ]);
//
//        if (count(Product::find()->where(['product_group_id' => $id, 'deleted_at' => null])->all()) > 0) {
//            return $this->render('../dependence/index', [
//                'dataProvider' => $dataProvider,
//                'searchModel' => null,
//            ]);
//
//        } else {
//            if ($this->findModel($id)->changeStatus()) {
//                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Product Group Status Changed Successfully.'));
//            } else {
//                Yii::$app->getSession()->setFlash('error', Yii::t('app', 'Product Group Status Change was Unsuccessful.'));
//            }
//
//            $query = Product::find()->where(['product_group_id' => $id]);
//
//            $dataProvider = new ActiveDataProvider([
//                'query' => $query,
//                //'sort' => ['defaultOrder' => ['id' => SORT_DESC]],
//            ]);
//
//            return $this->render('../dependence/index', [
//                'dataProvider' => $dataProvider,
//                'searchModel' => null,
//            ]);
//        }
//    }

}

modules/admin/views/product-group/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\form\ProductGroupForm $model
 * @var yii\bootstrap\ActiveForm $form
 */

?>

<div class="product-group-form">

    <?php $form = ActiveForm::begin([
        'id' => 'ProductGroup',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-lg-3',
                'wrapper' => 'col-lg-9',
                'error' => '',
                'hint' => '',
            ],
        ],
        'enableClientValidation' => false,
    ]); ?>

    <?= Html::hiddenInput('ru', ReturnUrl::getRequestToken()); ?>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <hr class="hr">
            <h1>Product Group</h1>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 oziris-block">
            <div class="row align-left" style="padding-top: 20px">
                <?= $form->field($model->productgroup, 'show_on_menu')->checkbox()?>
                <?= $form->field($model->productgroup, 'product_group_name')->textInput(['maxlength' => true]) ?>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <h1>Product Group Translation</h1>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 oziris-block">
            <div class="row" style="padding-top: 20px">
                <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                $form->field($model->productgrouptranslation, 'language_id')->widget(\kartik\select2\Select2::classname(), [
                    'name' => 'class_name',
                    'model' => $model,
                    'attribute' => 'language_id',
                    'data' => \yii\helpers\ArrayHelper::map(app\models\Language::find()->all(), 'id', 'name'),
                    'options' => [
                        'placeholder' => Yii::t('app', 'Type to autocomplete'),
                        'multiple' => false,
                    ]
                ]); ?>

                <?= $form->field($model->productgrouptranslation, 'product_group_name')->textInput(['maxlength' => true]) ?>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="pull-right" style="padding-top: 20px">
                <?= Html::submitButton('<span class="fa fa-check"></span> ' . ($model->productgroup->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')), [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-oziris-save'
                ]); ?>
                <?php if ($model->productgroup->isNewRecord) echo Html::a('<span class="fa fa-times"></span> ' . Yii::t('app', 'Cancel'), ReturnUrl::getUrl(['index']), ['class' => 'btn btn-oziris-normal']) ?>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/product-group/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\ProductGroup $model
 */

$this->title = Yii::t('app', 'Create Product Group');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Product Groups'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-group-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]); ?>

</div>

modules/admin/views/product-group/index.php
<?php

use app\models\Product;
use kartik\grid\ActionColumn;
use kartik\grid\BooleanColumn;
use kartik\grid\DataColumn;
use kartik\grid\GridView;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\ProductGroup $model
 * @var app\models\search\ProductGroupSearch $searchModel
 */

$this->title = Yii::t('app', 'Product Groups');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="product-group-index">
    <div class="clearfix">
        <table width="100%">
            <tr>
                <td>
                    <h1 class="pull-left"><?= $this->title ?></h1>
                </td>
            </tr>
        </table>
        <hr class="hr">
    </div>
    <div class="text-center">
        <?= GridView::widget([
            'layout' => '{summary}{pager}{items}{pager}',
            'export' => false,
            'responsive' => true,
            'hover'=>true,
            'dataProvider' => $dataProvider,
            'pager' => [
                'class' => yii\widgets\LinkPager::className(),
                'firstPageLabel' => Yii::t('app', 'First'),
                'lastPageLabel' => Yii::t('app', 'Last'),
            ],
            'filterModel' => $searchModel,
            'columns' => [
                // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
                [
                    'class' => DataColumn::className(),
                    'attribute' => 'product_group_name',
                    'value' => function ($model) {
                        if ($rel = $model->getId()->one()) {
                            return Html::a($rel->product_group_name, ['product-group/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                        } else {
                            return '';
                        }
                    },
                    'format' => 'raw',
                ],
                [
                    'class' => DataColumn::className(),
                    'attribute' => 'deleted_at',
                    'label' => 'Status',
                    'value' => function ($model) {
                        if ( $model->deleted_at == null) {

                            $dependent_products = count(Product::find()->where(['product_group_id' => $model->id, 'deleted_at' => null])->all());

                            return Html::a('<span class="glyphicon glyphicon-ok translated"></span>', ['product-group/change-status', 'id' => $model->id,],['title'=>Yii::t('app', 'Disable Product Group'), 'data-confirm' => Yii::t('kvgrid', 'Are you sure to disable this product group ?')]);
                        } else {
                            return Html::a('<span class="glyphicon glyphicon-remove not-translated"></span>', ['product-group/change-status', 'id' => $model->id,],['title'=>Yii::t('app', 'Enable Product Group'), 'data-confirm' => Yii::t('kvgrid', 'Are you sure to enable this product group?')]);
                        }
                    },
                    'format' => 'raw',
                ],
                ['class' => ActionColumn::className() ,
                    'template' => '{update}',
                    'contentOptions' => ['nowrap' => 'nowrap']
                ],
            ],
        ]); ?>
    </div>

</div>

modules/admin/views/product-group/update.php
<?php

use yii\helpers\Html;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\ProductGroup $model
 */

$this->title = Yii::t('app', 'Update') . ' ' . Yii::t('app', 'Product Group') . ' ' . $model->productgroup->product_group_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Product Groups'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->productgroup->id, 'url' => ['view', 'id' => $model->productgroup->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="product-group-update">

    <?= $this->render('@app/views/layouts/_menu', ['model'=>$model->productgroup]); ?>
    <?php echo $this->render('_form', [
        'model' => $model,
    ]); ?>

</div>

modules/admin/views/product-group/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\form\ProductGroupForm $model
 */

$this->title = Yii::t('app', 'Product Group') . ' ' . $model->productgroup->product_group_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Product Groups'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-group-view">

    <?= $this->render('@app/views/layouts/_menu', ['model'=>$model->productgroup]); ?>
    <?= DetailView::widget([
        'model' => $model->productgroup,
        'attributes' => [
            'product_group_name',
            [
                'attribute' => 'show_on_menu',
                'format' => 'raw',
                'value' => $model->productgroup->show_on_menu ? '<span class="label label-success">Yes</span>' : '<span class="label label-danger">No</span>',
                'widgetOptions' => [
                    'pluginOptions' => [
                        'onText' => 'Yes',
                        'offText' => 'No',
                    ]
                ],
                'labelColOptions' => ['style' => 'width:15.8%'],
            ],
            [
                'attribute' => 'created_at',
                'format' =>  ['datetime', 'php:d/m/yy h:m:s '],
                'options' => ['width' => '100px']
            ],
            [
                'attribute' => 'updated_at',
                'format' =>  ['datetime', 'php:d/m/yy h:m:s '],
                'options' => ['width' => '100']
            ],
        ],
    ]); ?>

    <?= DetailView::widget([
        'model' => $model->productgrouptranslation,
        'attributes' => [
            'product_group_name',
        ],
    ]);
    ?>
</div>