modules/admin/controllers/IngredientController.php
<?php

namespace app\modules\admin\controllers;
use app\models\BatchIngredient;
use app\models\form\IngredientForm;
use app\models\IngredientGroup;
use app\models\IngredientTranslation;
use cornernote\returnurl\ReturnUrl;
use Yii;
use yii\filters\AccessControl;
use app\models\Ingredient;
use app\models\ProductIngredient;

/**
 * This is the class for controller "app\controllers\IngredientController".
 */
class IngredientController extends \app\modules\admin\controllers\base\IngredientController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['guest']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'update-percentage' ,  'populate-ingredients-dropdown', 'add-product-ingredient', 'get-product-ingredients', 'delete-product-ingredient','get-ingredients-for-batch','populate-ingredient-groups-dropdown'],
                        'roles' => ['admin']
                    ]
                ]
            ]
        ];
    }

    public $ingredientTranslation;

    public function actionView($id)
    {
        $model = $this->findModel($id);
        $modelTranslation = IngredientTranslation::find()->where(['ingredient_id' => $id])->one();
        $ingredientModel = new IngredientForm();
        $ingredientModel->setIngredient($model);
        $ingredientModel->setIngredientTranslation($modelTranslation);
        return $this->render('view', ['model' => $ingredientModel]);
    }

    /**
     * Updates an existing Ingredient model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $ingredientModel = new IngredientForm();
        $ingredientModel->scenario = 'update';
        if (Yii::$app->request->post()) {
            $model->attributes = $_POST['Ingredient'];
            if($model->save(true)){
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Ingredient has been '.$ingredientModel->scenario.'d .'));
                if(Yii::$app->request->post()['IngredientTranslation']['language_id']!=''){
                    $this->ingredientTranslation = IngredientTranslation::find()->where(['ingredient_id' => $model->id, 'language_id' => $_POST['IngredientTranslation']['language_id'] ])->one();
                    if (isset($this->ingredientTranslation)) {
                        $this->ingredientTranslation->attributes = $_POST['IngredientTranslation'];
                        $this->ingredientTranslation->ingredient_id = $model->id;
                    } else {
                        $this->ingredientTranslation = new IngredientTranslation();
                        $this->ingredientTranslation->attributes = $_POST['IngredientTranslation'];
                        $this->ingredientTranslation->ingredient_id = $model->id;
                    }
                    if($this->ingredientTranslation->save(false)) {
                        Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Ingredient has been '.$ingredientModel->scenario.'d and translated.'));
                    }
                }
                $ingredientModel->setIngredient($model);
                $ingredientModel->setIngredientTranslation($this->ingredientTranslation);
                return $this->redirect(['view', 'id' => $model->id, 'ru' => ReturnUrl::getRequestToken()]);
            }
        }
        $ingredientModel->setIngredient($model);
        $ingredientModel->setIngredientTranslation($this->ingredientTranslation);
        return $this->render('update', ['model' => $ingredientModel]);
    }

    /**
     * Creates a new Ingredient model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Ingredient;
        $ingredientModel = new IngredientForm();
        $ingredientModel->scenario = 'create';
        if (Yii::$app->request->post()) {
            $model->attributes = $_POST['Ingredient'];
            if($model->save()){
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Ingredient has been '.$ingredientModel->scenario.'d .'));
                if(Yii::$app->request->post()['IngredientTranslation']['language_id']!=''){
                    $this->ingredientTranslation = new IngredientTranslation();
                    $this->ingredientTranslation->attributes = $_POST['IngredientTranslation'];
                    $this->ingredientTranslation->ingredient_id = $model->id;
                    if($this->ingredientTranslation->save()) {
                        Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Ingredient has been '.$ingredientModel->scenario.'d and translated.'));
                    }
                }
                $ingredientModel->setIngredient($model);
                $ingredientModel->setIngredientTranslation($this->ingredientTranslation);
                return $this->redirect(['view', 'id' => $model->id, 'ru' => ReturnUrl::getRequestToken()]);
            }
        }
        return $this->render('create', ['model' => $ingredientModel]);
    }

    public function actionPopulateIngredientGroupsDropdown()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $groups = IngredientGroup::find()->all();
        $results = [];
        $results[] = ['id' => '', 'text' => ''];
        foreach ($groups as $group) {
            $results[] = ['id' => $group->id, 'text' => $group->name];
        }
        return ['results' => $results];
    }

    public function actionPopulateIngredientsDropdown()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $ingredients = Ingredient::find()->where(['group_id' => $_POST['group_id']])->all();

        $results = [];
        $results[] = ['id' => '', 'text' => ''];
        foreach ($ingredients as $ingredient) {
            $results[] = ['id' => $ingredient->id, 'text' => $ingredient->name];
        }
        return ['results' => $results];
    }

    /**
     * Adds a new ProductIngredient  model.
     * @return mixed $productIngredient;
     */
    public function actionAddProductIngredient()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $ingredient_id = Ingredient::find()->where(['name' => $_POST['ingredient'] ])->one();

        if(!isset($ingredient_id)){
            $ingredient_id = $_POST['ingredient'];
        }

        $model = ProductIngredient::find()->where(['product_id' => $_POST['product_id'], 'ingredient_id' => $ingredient_id])->one();
        if(!isset($model)){
            $model = new ProductIngredient();
            $model->scenario = 'create';

            if(!is_numeric($_POST['group']) && $_POST['group']!=''){
                $ingredientGroup =IngredientGroup::find()->where(['name' => $_POST['group']])->one();
                if(!isset($ingredientGroup)){
                    $ingredientGroup = new IngredientGroup();
                    $ingredientGroup->name = $_POST['group'];
                    $ingredientGroup->save(false);
                }

            }

            if(!is_numeric($_POST['ingredient']) && $_POST['ingredient']!=''){
                $ingredient =Ingredient::find()->where(['name' => $_POST['ingredient']])->one();
                if(!isset($ingredient)){
                    $ingredient = new Ingredient();
                    $ingredient->name = $_POST['ingredient'];
                    $ingredient->group_id = (is_numeric($_POST['group']!='')) ? $_POST['group'] : $ingredientGroup->id;
                    $ingredient->save(false);
                }

            }
            if(isset($ingredientGroup) && isset($ingredient)){
                $model->product_id = $_POST['product_id'];
                $model->percentage = $_POST['percentage'];
                $model->ingredient_id = $ingredient->id;
                $model->save(false);
            }

            $productIngredient = [
                'id'=> $model->id,
                'ingredient' => $model->ingredient->name,
                'percentage' => $model->percentage,
                'ingredient-group' => $model->ingredient->group->name,
            ];
            return $productIngredient;
        }else{
            return false;
        }


    }

    /**
     * Deletes an existing OrderItem model.
     * @return boolean
     */
    public function actionDeleteProductIngredient()
    {
        return ProductIngredient::find()->where(['id'=>$_POST])->one()->delete();
    }


    /**
     * Edit Percentage Value .
     * @return boolean
     */
    public function actionUpdatePercentage()
    {
        $productIngredient =  ProductIngredient::find()->where(['id'=>$_POST['id']])->one();
        $productIngredient->percentage = $_POST['percentage'];

        return $productIngredient->save(false);
    }



    /**
     * Returns all existing ProductIngredient models.
     * @return ProductIngredient[]
     */
    public function actionGetProductIngredients()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $ingredients = ProductIngredient::findAll(['product_id' => $_POST['product_id']]);
        $productIngredients = [];

modules/admin/views/ingredient/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\form\IngredientForm $model
 * @var yii\bootstrap\ActiveForm $form
 */

?>

<div class="ingredient-form">
    <?php $form = ActiveForm::begin([
        'id' => 'Ingredient',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-lg-4',
                'wrapper' => 'col-lg-8',
                'error' => '',
                'hint' => '',
            ],
        ],
        'enableClientValidation' => false,
    ]); ?>

    <?= Html::hiddenInput('ru', ReturnUrl::getRequestToken()); ?>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <hr class="hr">
            <h1>Ingredient</h1>
        </div>
        <div class="col-lg-1"></div>
    </div>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 oziris-block">
            <div class="row" style="padding-top: 20px">
                <div class="col-lg-5">
                    <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                    $form->field($model->getIngredient(), 'group_id')->widget(\kartik\select2\Select2::classname(), [
                        'name' => 'class_name',
                        'model' => $model->getIngredient(),
                        'attribute' => 'group_id',
                        'data' => \yii\helpers\ArrayHelper::map(app\models\IngredientGroup::find()->all(), 'id', 'name'),
                        'options' => [
                            'placeholder' => Yii::t('app', 'Type to autocomplete'),
                            'multiple' => false,
                        ]
                    ]); ?>
                </div>
                <div class="col-lg-7">
                    <?= $form->field($model->getIngredient(), 'name')->textInput(['maxlength' => true]) ?>
                </div>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <h1>Ingredient Translation</h1>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10 oziris-block">
            <div class="row" style="padding-top: 20px">
                <div class="col-lg-5">
                    <?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
                    $form->field($model->ingredienttranslation, 'language_id')->widget(\kartik\select2\Select2::classname(), [
                        'name' => 'class_name',
                        'model' => $model->ingredienttranslation,
                        'attribute' => 'language_id',
                        'data' => \yii\helpers\ArrayHelper::map(app\models\Language::find()->all(), 'id', 'name'),
                        'options' => [
                            'placeholder' => Yii::t('app', 'Type to autocomplete'),
                            'multiple' => false,
                        ]
                    ]); ?>
                </div>
                <div class="col-lg-7">
                    <?= $form->field($model->ingredienttranslation, 'name')->textInput(['maxlength' => true]) ?>
                </div>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="pull-right" style="padding-top: 20px">
                <?= Html::submitButton('<span class="fa fa-check"></span> ' . ($model->getIngredient()->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')), [
                    'id' => 'save-' . $model->getIngredient()->formName(),
                    'class' => 'btn btn-oziris-save'
                ]); ?>
                <?php if ($model->getIngredient()->isNewRecord) echo Html::a('<span class="fa fa-times"></span> ' . Yii::t('app', 'Cancel'), ReturnUrl::getUrl(['index']), ['class' => 'btn btn-oziris-normal']) ?>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/ingredient/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\Ingredient $model
 */

$this->title = Yii::t('app', 'Create Ingredient');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Ingredient'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="ingredient-create">
    <?= $this->render('@app/views/layouts/_menu', ['model' => $model]) ?>
    <?= $this->render('_form', ['model' => $model,]); ?>
</div>

modules/admin/views/ingredient/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ButtonDropdown;
use yii\grid\GridView;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\IngredientSearch $searchModel
 */

$this->title = Yii::t('app', 'Ingredients');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="ingredient-index">

    <div class="clearfix">

        <table width="100%">
            <tr>
                <td>
                    <h1 class="pull-left"><?= $this->title ?></h1>
                </td>
                <td>
                    <div class="pull-right">
                        <?= Html::a('<span class="fa fa-plus"></span> ' . Yii::t('app', 'Create') . ' ' . Yii::t('app', 'Ingredient'), ['create', 'ru' => ReturnUrl::getToken()], ['class' => 'btn btn-oziris']) ?>
                    </div>
                </td>
            </tr>
        </table>
        <hr class="hr">
    </div>

    <div class="text-center">
        <?= \kartik\grid\GridView::widget([
            'layout' => '{summary}{pager}{items}{pager}',
            'dataProvider' => $dataProvider,
            'pager' => [
                'class' => yii\widgets\LinkPager::className(),
                'firstPageLabel' => Yii::t('app', 'First'),
                'lastPageLabel' => Yii::t('app', 'Last'),
            ],
            'filterModel' => $searchModel,
            'responsive' => true,
            'hover'=>true,
            'export' => false,
            'columns' => [
                [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'id',
                    'value' => function ($model) {
                        return Html::a($model->id, ['ingredient/view', 'id' => $model->id,], ['data-pjax' => 0]);
                    },
                    'format' => 'raw',
                ],
                [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'group_id',
                    'label' => 'Ingredient Group',
                    'value' => function ($model) {
                        return Html::a($model->group->name, ['ingredient/view', 'id' => $model->id,], ['data-pjax' => 0]);

                    },
                    'format' => 'raw',
                ],
                [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'name',
                    'label' => 'Ingredient Name',
                    'value' => function ($model) {
                        return Html::a($model->name, ['ingredient/view', 'id' => $model->id,], ['data-pjax' => 0]);

                    },
                    'format' => 'raw',
                ],
                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{update}',
                    'contentOptions' => ['nowrap' => 'nowrap']
                ],
            ],
        ]); ?>
    </div>

</div>

modules/admin/views/ingredient/ingredients.php
<?php

use app\widgets\JavaScript;
use kartik\select2\Select2;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use cornernote\returnurl\ReturnUrl;
use yii\helpers\Url;

/**
 * @var yii\web\View $this
 * @var app\models\Product $model
 * @var yii\bootstrap\ActiveForm $form
 */

?>

    <div class="text-center" id="order-items-div">

        <?= Html::hiddenInput('ru', ReturnUrl::getRequestToken()); ?>
        <div class="row">
                <h1 class="pull-left">Ingredients</h1>
        </div>

        <div class="row oziris-block">
            <div class="row">
                <div style="padding-left: 30px" class="col-lg-4">
                    <label class="control-label">Select Ingredient Group</label>
                    <?=
                        Select2::widget([
                            'id' => 'ingredient-group',
                            'name' => 'ingredient-group',
                            'data' => \yii\helpers\ArrayHelper::map(app\models\IngredientGroup::find()->all(), 'id', 'name'),
                            'options' => [
                                'placeholder' => Yii::t('app', 'Type to autocomplete'),
                                'multiple' => false,
                            ],
                            'pluginOptions' => [
                                'tags' => true,
                            ],
                            'pluginEvents' => [
                                'select2:select' => 'function(e) { populateIngredients(); }',
                            ]
                        ]);
                    ?>
                </div>

                <div class="col-lg-4" id="ingredients-div">
                    <label class="control-label">Select Ingredient</label>
                    <?=
                        Select2::widget([
                            'id' => 'ingredient',
                                'name' => 'ingredient',
                                'data' => \yii\helpers\ArrayHelper::map(app\models\Ingredient::find()->all(), 'id', 'name'),
                                'options' => [
                                    'placeholder' => Yii::t('app', 'Type to autocomplete'),
                                    'multiple' => false,
                                ],
                                'pluginOptions' => [
                                    'tags' => true,
                                ],
                        ]);
                    ?>
                </div>

                <div class="col-lg-2" id="ingredients-div">
                    <label class="control-label">Percentage</label>
                    <input type="text" id="txtIngredientPercentage">
                </div>

                <div class="col-lg-2" style="padding-top: 30px; padding-right: 30px">
                    <?= Html::button(Yii::t('app', 'Add'), [
                        'id' => 'btnAddIngredient',
                        'class' => 'btn btn-oziris-save btn-xs',
                        'style' => ['width' => '100%']
                    ]); ?>
                </div>
            </div>

            <div class="row" style="padding-top: 10px; padding-right: 30px ; padding-left: 30px">

                <table id="tblIngredients" class="kv-grid-table table table-bordered table-striped kv-table-wrap">
                    <thead>
                    <tr>
                        <th>Ingredient Group</th>
                        <th>Ingredient</th>
                        <th>Percentage</th>
                        <th width="50px"></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
<?php JavaScript::begin(); ?>
    <script>

        function generateIngredientsRow(data) {
            var row = '';

            row += "<tr>";
            row += "<td hidden='hidden'>" + data['id'] + "</td>";
            row += "<td>" + data['ingredient-group'] + "</td>";
            row += "<td>" + data['ingredient'] + "</td>";
            row += "<td> <input data='" + data.id + "' type='text' id='product" + data['id'] + "' value='"+data['percentage']+"'> </input> </td>";
            row += "<td><button type='button' style='width: 95px' id='update-percentage' class='glyphicon glyphicon-edit btn btn-oziris-save btn-xs' data='" + data.id + "'></button><button type='button' style='width: 95px' id='delete-ingredient' class='glyphicon glyphicon-trash btn btn-oziris-delete btn-oziris-delete-sm btn-xs' data='" + data.id + "'></button></td>";
            row += "</tr>";

            return row;
        }


        function populateIngredientGroups() {

            $('#ingredients-div').addClass('disabled');
            $.ajax({
                url: '<?= Url::to(['ingredient/populate-ingredient-groups-dropdown']); ?>', // point to server-side PHP script
                type: 'post',
                success: function (data) {
                    $('#ingredient-group').find('option').remove().end();
                    $('#ingredient').find('option').remove().end();
                    $.each(data.results, function (i, item) {
                        $('#ingredient-group').append($('<option>', {
                            value: item.id,
                            text: item.text
                        }));
                    });
                }
            });
        }

        function populateIngredients() {

            $('#ingredients-div').addClass('disabled');
            $.ajax({
                url: '<?= Url::to(['ingredient/populate-ingredients-dropdown']); ?>', // point to server-side PHP script
                data: {
                    group_id: $('#ingredient-group').find(":selected").val()
                },
                type: 'post',
                success: function (data) {
                    $('#ingredient').find('option').remove().end();
                    $.each(data.results, function (i, item) {
                        $('#ingredient').append($('<option>', {
                            value: item.id,
                            text: item.text
                        }));
                    });

                    $('#ingredients-div').removeClass('disabled');
                }
            });
        }

        function getAllItems() {

            var htmlString = '';
            $.ajax({
                url: '<?= Url::to(['ingredient/get-product-ingredients']); ?>', // point to server-side PHP script
                data: {product_id: <?= $model->id; ?>},
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    console.log('ingredients');
//                        console.log(data.ingredients);
                    if (data != null) {
                        $.each(data.ingredients, function (i, item) {
                            console.log(item);
                            htmlString += generateIngredientsRow(item);
                        });
                    }
                    $("#tblIngredients").find('tbody').append(htmlString);
                }
            });

        }

        if ($('#save-ProductForm').text().trim() == 'Save') {
            getAllItems();
            $("#btnAddIngredient").click(function () {
                var htmlString = '';
                if ($('#ingredient').find(":selected").val() == '' || $('#ingredient').find(":selected").text() == '') {
                    alert('Please Select an Ingredient');
                } else {
                    $.ajax({
                        url: '<?= Url::to(['ingredient/add-product-ingredient']); ?>', // point to server-side PHP script
                        data: {
                            group: $('#ingredient-group').find(":selected").text(),
                            percentage: $('#txtIngredientPercentage').val(),
                            ingredient: $('#ingredient').find(":selected").text(),
                            product_id: <?= ($model->id); ?>
                        },
                        type: 'post',
                        dataType: 'json',
                        success: function (data) {
                            console.log(data);
                            if (data != null) {
                                if(data == false){
                                    alert('Selected Ingredient already added to Product');
                                }else{
                                    $('#ingredient-group').val('').change();
                                    $('#ingredient').val('').change();
                                    populateIngredientGroups();
                                    htmlString += generateIngredientsRow(data);
                                    $("#tblIngredients").find('tbody').append(htmlString);


                                }
                            }
                        }
                    });
                }
            });

            $(document).on("click", "#update-percentage", function () {

                id = $(this).attr('data');
                percentage = $("#product"+id).val();

                if (confirm("Are you sure?")) {
                    $.ajax({
                        url: '<?= Url::to(['ingredient/update-percentage']); ?>', // point to server-side PHP script
                        data: {id , percentage},
                        type: 'post',
                        dataType: 'json',
                        success: function (data) {
                            if (data == 1){
                                alert("Ingredient Percentage updated successfully!");
                            }

                        }
                    });
                }
            });



            $(document).on("click", "#delete-ingredient", function () {
                console.log($(this).parent().parent());
                if (confirm("Are you sure?")) {
                    row = $(this).parent().parent();
                    $.ajax({
                        url: '<?= Url::to(['ingredient/delete-product-ingredient']); ?>', // point to server-side PHP script
                        data: {id: $(this).attr('data')},
                        type: 'post',
                        dataType: 'json',
                        success: function (data) {
                            if (data == '1') {
                                console.log(this);
                                row.remove();

                            }
                        }
                    });
                }
            });

            function generateTotals() {

//                $('#lblSubTotal').text(subtotal);
//                $('#lblTax').text(tax);
//                $('#lblTotal').text(total);
            }


        }

    </script>
<?php JavaScript::end(); ?>

modules/admin/views/ingredient/update.php
<?php

use yii\helpers\Html;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\form\IngredientForm $model
 */

$this->title = Yii::t('app', 'Update') . ' ' . Yii::t('app', 'Ingredient') . ' ' . $model->getIngredient()->name;

?>
<div class="ingredient-update">

    <?= $this->render('@app/views/layouts/_menu', ['model' => $model->getIngredient()]) ?>
    <?php echo $this->render('_form', ['model' => $model,]); ?>

</div>

modules/admin/views/ingredient/view-ingredients.php
<?php

/**
 * @var yii\web\View $this
 * @var app\models\ProductIngredient[] $model
 * @var yii\bootstrap\ActiveForm $form
 */
use cornernote\returnurl\ReturnUrl;
use dmstr\helpers\Html;
use Symfony\Component\Console\Input\Input;

?>

<div class="text-center" id="product-ingredient-div">
    <div class="row">
            <h1 class="pull-left">Ingredients</h1>
    </div>
    <div class="row">
        <table class="kv-grid-table table table-bordered table-striped kv-table-wrap">
            <thead>
            <tr>
                <th colspan="2">Ingredients</th>
            </tr>
        <tr>
                <th>Ingredient Name</th>
                <th>Ingredient Group</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($model as $index => $ingredient) { ?>
                <tr>
                    <td style="width: 30%"><label class="control-label"><?= $ingredient->ingredient->name ?></label></td>
                    <td style="width: 30%"><label class="control-label"><?= $ingredient->ingredient->group->name?></label></td>
                </tr>
            <?php } ?>

            </tbody>
        </table>
    </div>
</div>