modules/admin/controllers/OrderController.php
<?php

namespace app\modules\admin\controllers;
use app\models\Address;
use app\models\AppUser;
use app\models\base\AppUserDeviceInfo;
use app\models\Order;
use app\models\base\ProductLocationAttribute;
use app\models\Language;
use app\models\OrderItem;
use app\models\OrderStatus;
use app\models\OrderStatusTime;
use app\models\search\OrderSearch;
use app\models\search\ProductSearch;
use app\utils\BestonSMSSender;
use app\utils\csvToArray;
use app\utils\FetchContinentFromCountryCode;
use app\utils\PushNotificationSender;
use DateTime;
use dmstr\bootstrap\Tabs;
use dmstr\db\tests\unit\Product;
use kartik\mpdf\Pdf;
use Yii;
use yii\filters\AccessControl;
use yii\httpclient\Client;

/**
 * This is the class for controller "app\controllers\OrderController".
 */
class OrderController extends \app\modules\admin\controllers\base\OrderController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'report', 'stock-analysis', 'ecommerce-reports','update'],
                        'roles' => ['accounts', 'guest']
                    ],
                    [
                        'allow' => false,
                        'actions' => ['update'],
                        'roles' => ['restricted-order-access']
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'report' , 'create', 'update', 'delete', 'create-order-item' , 'delete-order-item' , 'generate-manifest', 'stock-transfer' , 'generate-order-csv', 'generate-stock-csv' ,  'add-stock-transfer-item',  'generate-order-item-csv', 'print-label', 'stock-analysis', 'load-stock-grid', 'ecommerce-reports', 'print-orders'],
                        'roles' => ['admin']
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        Tabs::clearLocalStorage();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Finds the Order model based on woo_order_id.
     * @param integer $woo_order_id
     * @return Order the loaded model
     */
    protected function findOrder($woo_order_id)
    {
        $model = Order::find()->where(['woo_order_id' => $woo_order_id])->one();
        return $model;
    }

    public function actionEcommerceReports() {
        return $this->redirect('../reports/ecommerce');
    }

    public function actionStockTransfer() {

        $shipping_address = new Address();
        $shipping_address->type = 'Shipping';
        $shipping_address->save(false);

        $billing_address = new Address();
        $billing_address->type = 'Billing';
        $billing_address->save(false);

        $order = new Order();
        $order->shipping_address_id = $shipping_address->id;
        $order->billing_address_id = $billing_address->id;
        $order->customer_id = 1;
        $order->status_id = 1;
        $order->trading_channel = 'B2B';
        $order->save(false);





        return $this->render('stock-transfer');
    }

    public function actionStockAnalysis() {
        $searchModel = new ProductSearch;

        $dataProvider = $searchModel->stockSearch(Yii::$app->request->get());
//        $dataProvider->query->andWhere(['is_collection' => 0 ]);
        $dataProvider->setPagination([
                'defaultPageSize' => 50,
                'pageSizeLimit'=>50]
        );
        return $this->render('stock', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);

//        return $this->render('stock');
    }

    public function actionCreateOrderItem(){

        $model = new OrderItem();
        $model->scenario = 'create';
        $model->attributes = $_POST;
        if($model->save()){
            Yii::$app->session->setFlash('success','Order Item Added Successfully', true);
            $this->redirect(['update', 'id'=>$_POST['model_id']]);
        }

    }

    public function actionDeleteOrderItem($data,$id){
        OrderItem::find()->where(['id'=>$data])->one()->delete();
        Yii::$app->session->setFlash('success','Order Item Deleted Successfully', true);
        $this->redirect(['update', 'id'=>$id]);
    }

    public function actionLoadStockGrid(){
        $searchModel = new ProductSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->get());
        $dataProvider->query->andWhere(['is_collection' => 0 ]);
        $dataProvider->setPagination([
                'defaultPageSize' => 50,
                'pageSizeLimit'=>50]
        );
        return $this->renderAjax('stock-grid', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionReport($id) {

        $order = Order::find()->where(['woo_order_id' => $id])->one();

        $content = $this->renderPartial('_reportView',['order' => $order]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            'format' => Pdf::FORMAT_A4,
            'orientation' => Pdf::ORIENT_PORTRAIT,
            'destination' => Pdf::DEST_BROWSER,
            'content' => $content,
            'options' => ['title' => 'Hamper '.$id. ' Item Report'],
            'methods' => [
                'SetHeader'=>['Hamper '.$id. ' Item Report'],
                'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        $pdf->options = [
            'autoScriptToLang' => true,
            'ignore_invalid_utf8' => true,
            'tabSpaces' => 4,
            'autoLangToFont' => true,
        ];

        // return the pdf output as per the destination setting
        return $pdf->render();
    }


    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = 'update';
        $model->updated_at = time();

        if(Yii::$app->request->isPost){
//            if($model->woo_order_id < 10000000){
//                if($_POST['Order']['status_id'] == 8){
//                    if($_POST['Order']['status_id'] != $model->status_id & $model->customer->email_address != 'default' ){
//                        $devices_ios = AppUserDeviceInfo::find()->where(['user_id' => $model->customer_id, 'device_type' => 'iOS' ])->all();
//                        if( count($devices_ios) > 0 ){
//                            $notification = "Order Status has been changed to : ".OrderStatus::find()->where(['id' => $_POST['Order']['status_id']])->one()->description;
//                            PushNotificationSender::sendIOSNotification($devices_ios,$notification,$model->woo_order_id);
//                        }
//                        $devices_android = AppUserDeviceInfo::find()->where(['user_id' => $model->customer_id, 'device_type' => 'android' ])->all();
//                        if( count($devices_android) > 0 ){
//                            $notification = "Order ID ".$model->woo_order_id." has been changed to : ".OrderStatus::find()->where(['id' => $_POST['Order']['status_id']])->one()->description;
//                            PushNotificationSender::sendAndroidNotification($devices_android,$notification);
//                        }
//                        $sms_notification = "Order Status for Order # ".$model->woo_order_id." has been changed to : ".OrderStatus::find()->where(['id' => $_POST['Order']['status_id']])->one()->description;
//                        BestonSMSSender::sendSMSNotification($model->getBillingAddress()->one()->getContactNo(),$sms_notification) ;
//                    }
//                }
//            }


            if ($model->load(Yii::$app->request->post()) && $model->save()) {

                $orderStatusTime = OrderStatusTime::find()->where(['order_id' => $model->woo_order_id, 'status_id' => $model->status_id])->one();
                if(isset($orderStatusTime)){
                    $orderStatusTime->time = $model->updated_at;
                    $orderStatusTime->save();
                }

                if($model->woo_order_id < 10000000){
                    $client = new Client();
                    $response = $client->createRequest()
                        ->setMethod('post')
                        ->setUrl(getenv('SERVER_TYPE').'/update_order_details')
                        ->setData(
                            [
                                'order_id' => $model->woo_order_id,
                                'order_note' => $model->order_note,
                                'order_status' => $model->status->name,
                            ])->send();


                }
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'Order has been updated.'));

                return $this->redirect('index');
            }
        }
        return $this->render('update', ['model' =>$model]);
    }

    /**
     * Searches all Orders according to search criteria and generates Manifest CSV.
     * @return CSV Download link
     */
    public function actionGenerateManifest()
    {
        $searchModel = new OrderSearch();


modules/admin/views/order/_createForm.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use cornernote\returnurl\ReturnUrl;

/**
 * @var yii\web\View $this
 * @var app\models\Order $model
 * @var yii\bootstrap\ActiveForm $form
 */

?>

<div class="order-form">

    <?php $form = ActiveForm::begin([
        'id' => 'Order',
        'layout' => 'horizontal',
        'enableClientValidation' => false,
        'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-lg-2',
                'wrapper' => 'col-lg-10',
                'error' => '',
                'hint' => '',
            ],
        ],
    ]); ?>

    <?= Html::hiddenInput('ru', ReturnUrl::getRequestToken()); ?>
    <?= $form->errorSummary($model); ?>


    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <hr class="hr">
        </div>
        <div class="col-lg-1"></div>
    </div>

    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10  oziris-block">

            <div class="row">

                <div class="col-md-12">
                    <h1>Contact Name</h1>

                    <div class="col-md-6" style="padding-top: 20px">
                        <?= $form->field($model->billingAddress, 'first_name')->textInput(['maxlength' => true, 'name' => 'first_name']) ?>
                    </div>
                    <div class="col-md-6" style="padding-top: 20px">
                        <?= $form->field($model->billingAddress, 'last_name')->textInput(['maxlength' => true, 'name' => 'last_name']) ?>
                    </div>
                </div>

                <div class="col-md-6">
                    <h1>Billing Address</h1>
                    <?= $form->field($model->billingAddress, 'address_1')->textInput(['maxlength' => true, 'name' => 'address_1']) ?>
                    <?= $form->field($model->billingAddress, 'suburb')->textInput(['maxlength' => true, 'name' => 'suburb']) ?>
                    <?= $form->field($model->billingAddress, 'state')->textInput(['maxlength' => true, 'name' => 'state']) ?>
                    <?= $form->field($model->billingAddress, 'postcode')->textInput(['maxlength' => true, 'name' => 'postcode']) ?>
                    <?= $form->field($model->billingAddress, 'country')->textInput(['maxlength' => true, 'name' => 'country']) ?>
                    <?= $form->field($model->billingAddress, 'email')->textInput(['maxlength' => true, 'name' => 'email']) ?>
                    <?= $form->field($model->billingAddress, 'contact_no')->textInput(['maxlength' => true, 'name' => 'contact_no']) ?>
                </div>
                <div class="col-md-6">
                    <h1>Shipping Address</h1>
                    <?= $form->field($model->shippingAddress, 'address_1')->textInput(['maxlength' => true]) ?>
                    <?= $form->field($model->shippingAddress, 'suburb')->textInput(['maxlength' => true]) ?>
                    <?= $form->field($model->shippingAddress, 'state')->textInput(['maxlength' => true]) ?>
                    <?= $form->field($model->shippingAddress, 'postcode')->textInput(['maxlength' => true]) ?>
                    <?= $form->field($model->shippingAddress, 'country')->textInput(['maxlength' => true]) ?>
                </div>
            </div>


            <div class="row" style="padding-top: 20px">
                <div class="col-lg-12">
                    <?= $form->field($model, 'order_note')->textarea(['rows' => 6]) ?>
                </div>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>

    <?php if (!$model->isNewRecord){
            echo $this->render('../collection-item/order-item',['model' => $model]);
        }
     ?>
    <div class="row">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="pull-right" style="padding-top: 20px">
                <?= Html::submitButton('<span class="fa fa-arrow-right"></span> ' . ($model->isNewRecord ? Yii::t('app', 'Next') : Yii::t('app', 'Save')), [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-oziris-save'
                ]); ?>
                <?php if ($model->isNewRecord) echo Html::a('<span class="fa fa-times"></span> ' . Yii::t('app', 'Cancel'), ReturnUrl::getUrl(['index']), ['class' => 'btn btn-oziris-normal']) ?>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/order/_labelView.php
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body lang="zh-CN">
<?php
foreach($orders as $order){
?>

    <table width="100%">
        <tr style="border: 1px solid #000000">
            <th style="vertical-align: middle; text-align: left">
                <img width="120px" src="images/beston-logo.png" alt="Beston Market Place">
            </th>
            <th style="vertical-align: middle; text-align: left">
                <img width="130px" src="images/oziris-logo.png" alt="OZIRIS">
            </th>
            <th style="vertical-align: top ; text-align: right">
                <?php $imgsrc = 'order/qrcode/'.$order->qr_code?>
                <img src="<?= $imgsrc?>"  alt='Order QR Code' width='100px' height='100px'>
            </th>
        </tr>
        <tr>
            <td colspan="3">
            </td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                <p style="font-size: 16px; font-weight: bolder ; color: #ffffff ;background-color: #000000;">www.bestonmarketplace.com.au</p>
            </td>
        </tr>
        <tr>
            <td colspan="3">
            </td>
        </tr>
        <tr>
            <td colspan="3" height="100px" style="vertical-align: top">
                <table width="100%" >
                    <tr>
                        <th style="font-size: 14px; font-weight: bolder ; background-color: #000000; color: #ffffff">
                            Shipping Address
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <p style="text-align: justify ; font-size: 14px">
                                <b><?= $order->getShippingAddress()->one()->first_name . ' ' . $order->getShippingAddress()->one()->last_name ?></b><br>
                                <span><?= $order->getShippingAddress()->one()->address_1 ?></span><br>
                                <?php if ($order->getShippingAddress()->one()->address_2 != '') {
                                    echo $order->getShippingAddress()->one()->address_2;
                                }
                                ?>
                                <?= $order->getShippingAddress()->one()->suburb . ' ' . $order->getShippingAddress()->one()->state . ' ' . $order->getShippingAddress()->one()->postcode ?>
                                <br>
                                <?= $order->getShippingAddress()->one()->country ?>
                                <br>
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="3" height="100px" style="vertical-align: top">
                <table width="100%">
                    <tr>
                        <th style="font-size: 14px; font-weight: bolder ; background-color: #000000; color: #ffffff;">
                            Order Information
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <p style="text-align: justify ; font-size: 14px">
                                <b>Order Number : </b><?= $order->woo_order_id ?><br>
                                <b>Leave at door : </b><?= (($order->leave_at_door == '1') ? 'Yes' : 'No'); $order->leave_at_door ?><br>
                                <br>
                                <br>
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="3" height="100px" style="vertical-align: top" >
                <table width="100%">
                    <tr>
                        <th style="font-size: 14px; font-weight: bolder ; background-color: #000000; color: #ffffff">
                            Order Note
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <p style="text-align: justify ; font-size: 14px">
                                <?= $order->order_note ?><br>
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="3" style="vertical-align: top ; text-align: center">
                <p style="font-size: 16px; font-weight: bolder ; color: #ffffff ;background-color: #000000;">TASTY & FRAGILE HANDLE WITH CARE</p>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <br>
            </td>
        </tr>
        <tr style="border: 1px solid #000000">
            <td colspan="3" style="vertical-align: top ; text-align: center">
                <?php $barcode = preg_replace('/\s+/', '', 'order/barcode/'.$order->barcode).'.png' ?>
                <img src="<?= $barcode?>"  height="45px" alt='Order Bar Code'>
            </td>
        </tr>

    </table>

    <pagebreak />
<?php
}
?>
</body>

</html>

modules/admin/views/order/reports.php
<?php

use app\models\OrderStatus;
use app\widgets\JavaScript;
use cornernote\returnurl\ReturnUrl;
use kartik\daterange\DateRangePicker;
use kartik\grid\ActionColumn;
use kartik\grid\GridView;
use kartik\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

$this->title = Yii::t('app', 'Orders');
?>
<div class="address-create">

    <div class="product-index">
        <div class="clearfix">
            <div class="row">
                <div class="col-lg-12">
                    <table width="100%">
                        <tr>
                            <td>
                                <h1 class="pull-left"><?= $this->title ?></h1>
                            </td>
                            <td>
                                <div class="pull-right">

                                    <?= Html::button('Generate Manifest', ['class' => 'btn btn-oziris', 'id' => 'btnGenerateManifest']) ?>
                                    <a class='btn btn-oziris hidden' id="btnDownloadManifest">Download Manifest</a>
                                    <?= Html::button('Generate Labels', ['class' => 'btn btn-oziris', 'id' => 'btnPrintLabel']) ?>
                                    <a class='btn btn-oziris hidden' id="btnDownloadLabel">Download Labels</a>
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <hr class="hr">
        </div>
        <div class="table-responsive text-center">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'export' => false,
                'filterModel' => $searchModel,
                'bordered'=>true,
                'striped'=>true,
                'condensed'=>true,
                'responsive'=>true,
                'hover'=>true,
                'columns' => [
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'woo_order_id',
                        'contentOptions' => ['style' => 'width:70px;'],
                        'value' => function ($model) {
                            return Html::a($model->woo_order_id, ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                        },
                        'format' => 'raw',
                    ],
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'created_at',
                        'label' => 'Order Date',
                        'contentOptions' => ['style' => 'width:200px;'],
                        'filter' => DateRangePicker::widget([
                            'model' => $searchModel,
                            'attribute' => 'created_at',
                            'convertFormat' => true,
                            'pluginOptions' => [
                                'locale' => [
                                    'format' => 'd-M-y'
                                ],
                            ],
                        ]),
                        'value' => function ($model) {
                            return Html::a(date('d-M-y h:i a', $model->created_at), ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                        },
                        'format' => 'raw',
                    ],
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'status_id',
                        'filter'=>ArrayHelper::map(OrderStatus::find()->asArray()->all(), 'id', 'name'),
                        'contentOptions' => ['style' => 'width:150px;'],
                        'value' => function ($model) {
                           return Html::a($model->status->name, ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                        },
                        'format' => 'raw',
                    ],
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'updated_at',
                        'contentOptions' => ['style' => 'width:200px;'],
                        'filter' => DateRangePicker::widget([
                            'model' => $searchModel,
                            'attribute' => 'updated_at',
                            'convertFormat' => true,
                            'pluginOptions' => [
                                'locale' => [
                                    'format' => 'd-M-y'
                                ],
                            ],
                        ]),
                        'value' => function ($model) {
                            if((integer)$model->updated_at>0){
                                return Html::a(date('d-M-y h:i a', (integer)$model->updated_at), ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                            }else{
                                return '';
                            }

                        },
                        'format' => 'raw',
                    ],
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'customer_id',
                        'label' => 'Customer Email',
                        'contentOptions' => ['style' => 'width:200px;'],
                        'value' => function ($model) {
                                if($model->customer->email_address && $model->customer->email_address != 'default'){
                                    return Html::a($model->customer->email_address, ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                                }else if($model->customer->email_address == 'default'){
                                    return Html::a("Guest Checkout", ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                                }
                        },
                        'format' => 'raw',
                    ],
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'contact_no',
                        'contentOptions' => ['style' => 'width:200px;'],
                        'value' => function ($model) {
                                if($model->getBillingAddress()->one()){
                                    return Html::a($model->getBillingAddress()->one()->contact_no, ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                                }else{
                                    return '';
                                }
                        },
                        'format' => 'raw',
                    ],
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'order_note',
                        'value' => function ($model) {
                            return Html::a($model->order_note, ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                        },
                        'format' => 'raw',
                    ],
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'total_amount',
                        'label' => 'Total',
                        'contentOptions' => ['style' => 'width:50px;'],
                        'value' => function ($model) {
                            $formatter = new NumberFormatter('en_AU', NumberFormatter::CURRENCY);
                            return Html::a($formatter->formatCurrency($model->total_amount, 'AUD'), ['order/update', 'id' => $model->id,], ['data-pjax' => 0]);
                        },
                        'format' => 'raw',
                    ],

                    ['class' => ActionColumn::className(),
                        'template' => '{update}&nbsp;&nbsp;{duplicate}',
                        'buttons' => [
                            'duplicate' => function ($url, $model) {
                                return Html::a('<span class="glyphicon glyphicon-print"></span> ', ['report', 'id' => $model->woo_order_id], ['title' => Yii::t('app', 'Print Order'),]);
                            }
                        ],
                        'contentOptions' => ['nowrap' => 'nowrap']
                    ],
                ],
            ]); ?>
        </div>

    </div>
</div>


<?php JavaScript::begin(); ?>
<script>

    $('#btnGenerateManifest').on('click', function (event) {
        searchField = {};
        length = $('thead tr td').children().length;
        for (i = 1; i <= length; i++) {
            if($('thead tr td:nth-child(' + i + ') input').attr('name') != undefined){
                console.log($('thead tr td:nth-child(' + i + ') input').attr('name'));
                element = $('thead tr td:nth-child(' + i + ') input').attr('name');
//                console.log(element);

                key = element.substring((element.indexOf('[') + 1), element.indexOf(']'));
                searchField[key] = $('thead tr td:nth-child(' + i + ') input').val()
            }
        }

        searchField['status_id'] = $('select[name="OrderSearch[status_id]"]').val();
        console.log(searchField);
        $.ajax({
            url: '<?= Url::to(['order/generate-manifest']); ?>', // point to server-side PHP script
            data: searchField,
            type: 'post',
            success: function (php_script_response) {
                if (php_script_response) {
                    $('#btnGenerateManifest').addClass('hidden');
                    $('#btnDownloadManifest').removeClass('hidden');
                }
                console.log(php_script_response); // display response from the PHP script, if any
            },
            error: function (php_script_response) {
                console.log('error'); // display response from the PHP script, if any
                console.log(php_script_response);  // display response from the PHP script, if any
            }
        });
    });


    $('#btnPrintLabel').on('click', function (event) {
        searchField = {};
        length = $('thead tr td').children().length;
        for (i = 1; i <= length; i++) {
            if($('thead tr td:nth-child(' + i + ') input').attr('name') != undefined){
                element = $('thead tr td:nth-child(' + i + ') input').attr('name');
                key = element.substring((element.indexOf('[') + 1), element.indexOf(']'));
                searchField[key] = $('thead tr td:nth-child(' + i + ') input').val()
            }
        }
        searchField['status_id'] = $('select[name="OrderSearch[status_id]"]').val();

        $.ajax({
            url: '<?= Url::to(['order/print-label']); ?>',
            data: searchField,
            type: 'post',
            success: function (php_script_response) {
                    $('#btnPrintLabel').addClass('hidden');
                    $('#btnDownloadLabel').removeClass('hidden');
            },
            error: function (php_script_response) {
            }
        });
    });


    $('#btnDownloadManifest').on('click', function (event) {
        $('#btnGenerateManifest').removeClass('hidden');
        $('#btnDownloadManifest').addClass('hidden');

        $('#btnDownloadManifest').attr({target: '_blank', href: '<?= Url::to('@web/csv/manifest.csv'); ?>'});
    });

    $('#btnDownloadLabel').on('click', function (event) {
        $('#btnPrintLabel').removeClass('hidden');
        $('#btnDownloadLabel').addClass('hidden');

        $('#btnDownloadLabel').attr({target: '_blank', href: '<?= Url::to('@web/label.pdf'); ?>'});
    });

</script>
<?php JavaScript::end(); ?>